### ISSUE TITLE
Load pdf file to be read

### ISSUE THREAD

**Issue by Rafiah-n** [Rafiah-n/AcademiCal#5]
on the convert-doc-2 branch

Using Gradle and importing the relevant pdfbox package seems to not be working, potential problems:
- Gradle build file is not configured correctly
- Correct package and imports not used
- Gradle not syncing correctly

**Comment by Mikhovs** [comment]
[mat135-syllabus-f23.pdf](https://github.com/Rafiah-n/AcademiCal/files/13478006/mat135-syllabus-f23.pdf)

**Comment by ksaykili** [comment]
[COG250_Syllabus.docx](https://github.com/Rafiah-n/AcademiCal/files/13478011/COG250_Syllabus.docx)
[PSY290H1F_syllabus.pdf](https://github.com/Rafiah-n/AcademiCal/files/13478013/PSY290H1F_syllabus.pdf)
[STA220_Syllabus.pdf](https://github.com/Rafiah-n/AcademiCal/files/13478014/STA220_Syllabus.pdf)

**Comment by Rafiah-n** [comment]
tested and working
